dob_holiday:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DEV_DB_PATH', '/Users/randallchen/repos/portfolio/dev.duckdb') }}"
      threads: 1
      extensions:
        - parquet

    prod:
      type: duckdb
      path: "{{ env_var('DBT_PROD_DB_PATH') }}"
      threads: 4
      extensions:
        - parquet
